### ISSUE TITLE
Global keyboard shortcuts interfere with components in stories

### ISSUE THREAD

**Issue by mooski** [jsakamoto/BlazingStory#10]
In the scenario where you have a component which accepts keyboard input, the Blazing Story global keyboard shortcuts make it difficult or impossible to properly interact with the component.

For example, if you have a simple `input type="text"` field in the story and you try to type in it, every time you press the 'f' key it toggles fullscreen mode. Similarly, and even more frustratingly, every time you press backspace the browser goes back to the previous page, making it impossible to test certain scenarios.

Ideally I think global keyboard shortcuts shouldn't be triggered if any element in the iframe has focus. Failing that, would it just be possible to have the option to completely disable global keyboard shortcuts?

The only current workaround I'm aware of is just to open the story directly (iframe.html), for example using the 'Open canvas in new tab' button, but of course then you lose all the functionality that Blazing Story offers.

**Comment by jsakamoto** [comment]
@mooski Thank you for your feedback!

I released the new version of Blazing Story, ver.1.0.0 Preview 11, which might be able to mitigate your frustration.

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.11#release-body-tab

This version does not provide the option to disable global keyboard shortcuts, and global keyboard shortcuts still work even when the "iframe.html" has focus. But since this new version, if any _inputable_ element in "iframe.html" has focus, global keyboard shortcuts have been suppressed.

- See also: https://github.com/jsakamoto/BlazingStory/commit/d4d14d18b6c87b592c1b3417e66fc9dcc268f790#diff-080937c85ebb694aeba93d53b8e41b2ab663e769bc5e04c63619e0dac2929a73

I hope the new version will save you from such frustrating behavior of the Blazing Story.

**Comment by mooski** [comment]
@jsakamoto This is perfect - thank you once again for providing a solution and improving this great product!
