### ISSUE TITLE
razor.cs file not being picked up when component expects a generic type

### ISSUE THREAD

**Issue by NathanVG** [jsakamoto/BlazingStory#51]
I have a component Table that has a TValue prop for passing the type of array of objects being passed to the component. 
When I make a Table.razor.cs file for the documentation I can only pass TValue (public partial class Table<TValue>), in the story file itself I pass a locally declared type of Person. I think due to the differing types the file is not being picked up for the docs

**Comment by Namoshek** [comment]
I think this issue comes from the use of `FullName` on L39 here:

https://github.com/jsakamoto/BlazingStory/blob/821e874e6eb2e72fced0e4172e7607cfb48b3554/BlazingStory/Internals/Services/XmlDocComment/XmlDocCommentBase.cs#L34-L46

I've created a dotnetfiddle that shows the issue and a possible solution: https://dotnetfiddle.net/zJiwPZ

**Comment by jsakamoto** [comment]
@NathanVG @Namoshek Hi everyone,
I released the new version of the "Blazing Story," v.1.0.0 Preview 38, right now. 

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.38#releasenotes-body-tab

It must have fixed this issue. Could you try it out?
Thank you for your contributions!

**Comment by Namoshek** [comment]
Looks good to me, thank you for providing a quick fix for it! :rocket:
